spring-boot-workspace/first-spring-boot-web-application/src/main/java/com/springboot/web/firstspringbootwebapplication/models/ToDo.java
package com.springboot.web.firstspringbootwebapplication.models;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.validation.constraints.Size;

@Entity
public class ToDo {
	
	@Id
	@GeneratedValue
	private int id;
	private String user;
	
	@Size(min=10,message="Enter atleast 10 characters!")
	private String descr;
	
	public Date targetDate;
	private boolean isDone;
	public ToDo() {
		super();
	}
	public ToDo(int id, String user, String descr, Date targetDate, boolean isDone) {
		super();
		this.id = id;
		this.user = user;
		this.descr = descr;
		this.targetDate = targetDate;
		this.isDone = isDone;
	}
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getUser() {
		return user;
	}
	public void setUser(String user) {
		this.user = user;
	}
	public String getDescr() {
		return descr;
	}
	public void setDescr(String descr) {
		this.descr = descr;
	}
	public Date getTargetDate() {
		return targetDate;
	}
	public void setTargetDate(Date targetDate) {
		this.targetDate = targetDate;
	}
	public boolean isDone() {
		return isDone;
	}
	public void setDone(boolean isDone) {
		this.isDone = isDone;
	}
	@Override
	public boolean equals(Object obj) {
		if(this==obj)
			return true;
		if(obj==null || getClass() != obj.getClass() || ((ToDo)obj).id != this.id)
			return false;
		
		return true;
	}
	@Override
	public String toString() {
		return "ToDo [id=" + id + ", user=" + user + ", descr=" + descr + ", targetDate=" + targetDate + ", isDone="
				+ isDone + "]";
	}
}

spring-boot-workspace/first-spring-boot-web-application/src/main/java/com/springboot/web/firstspringbootwebapplication/controllers/ErrorController.java
package com.springboot.web.firstspringbootwebapplication.controllers;

import javax.servlet.http.HttpServletRequest;

import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.servlet.ModelAndView;

@Controller("error")
public class ErrorController {

	@ExceptionHandler(Exception.class)
		public ModelAndView handleException(HttpServletRequest request, Exception e, ModelMap model) {
			ModelAndView mv = new ModelAndView();
			mv.addObject("exception",e.getStackTrace());
			mv.addObject("url",request.getRequestURL());
			mv.setViewName("error");
			model.addAttribute("exception", e.getStackTrace());
			model.addAttribute("url", request.getRequestURL());
			return mv;
		}
	
}

spring-boot-workspace/first-spring-boot-web-application/src/main/java/com/springboot/web/firstspringbootwebapplication/controllers/TodoController.java
package com.springboot.web.firstspringbootwebapplication.controllers;

import java.text.SimpleDateFormat;
import java.util.Date;

import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.propertyeditors.CustomDateEditor;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.WebDataBinder;
import org.springframework.web.bind.annotation.InitBinder;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import com.springboot.web.firstspringbootwebapplication.models.ToDo;
import com.springboot.web.firstspringbootwebapplication.services.TodoRepo;

@Controller
//Dont need to store in session because of spring seecurity @SessionAttributes("name")
public class TodoController {

	
	@Autowired
	TodoRepo todoRepo;
	
	private String getLoggedInUserName(ModelMap model) {
		Object principal = SecurityContextHolder.getContext().getAuthentication().getPrincipal();
		if(principal instanceof UserDetails) {
			return ((UserDetails)principal).getUsername();
		}
		return principal.toString();
	}
	
	@InitBinder
	public void initBinder(WebDataBinder binder) {
		//Date format - dd/MM/yyyy
		SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
		binder.registerCustomEditor(Date.class, new CustomDateEditor(dateFormat, false));
	}
	
	@RequestMapping(value ="/list-todos", method = RequestMethod.GET)
	public String showTodos(ModelMap model) {
		model.put("activeTab", "list-todos");
		String name = getLoggedInUserName(model);
		model.put("todos", todoRepo.findByUser(name));
		return "list-todos";//directs to the JSP file list-todos
	}

	@RequestMapping(value ="/add-todo", method = RequestMethod.GET)
	public String showAddToDo(ModelMap model) {
		model.put("activeTab", "add-todo");
		model.addAttribute("todo", new ToDo(0,getLoggedInUserName(model),"",new Date(),false));
		return "todo";//directs to the JSP file
	}
	@RequestMapping(value ="/add-todo", method = RequestMethod.POST)
	public String addTodo(ModelMap model,@Valid ToDo todo, BindingResult result) {
		if(result.hasErrors()){
			model.addAttribute("todo", new ToDo(0,getLoggedInUserName(model),"",new Date(),false));
			model.addAttribute("errorMessage", "Enter atleast 10 characters!");
			return "todo";
		}
		String name = getLoggedInUserName(model);
		model.put("activeTab", "list-todos");
		todo.setUser(getLoggedInUserName(model));
		todoRepo.save(todo);
		//todoService.add(name, todo.getDescr(), todo.getTargetDate(), false);
		return "redirect:/list-todos";//Redirects to list-todos method showTodos.. rather than just the jsp file
	}
	@RequestMapping(value ="/delete-todo", method = RequestMethod.GET)
	public String deleteTodo(@RequestParam int id, ModelMap model) {
		todoRepo.delete(id);
		model.put("activeTab", "list-todos");
		return "redirect:/list-todos";
	}
	@RequestMapping(value ="/update-todo", method = RequestMethod.GET)
	public String showUpdateTodoPage(ModelMap model,@Valid ToDo todo, BindingResult result) {
		model.addAttribute("todo",todoRepo.findOne(todo.getId()));
		model.put("activeTab", "todo");
		return "todo";
	}
	@RequestMapping(value ="/update-todo", method = RequestMethod.POST)
	public String updateTodo(ModelMap model,@Valid ToDo todo, BindingResult result) {
		String name = getLoggedInUserName(model);
		todo.setUser(name);
		if(result.hasErrors()){
			model.addAttribute("todo", todo);
			model.addAttribute("errorMessage", "Enter atleast 10 characters!");
			return "todo";
		}
		model.put("activeTab", "list-todos");
		todoRepo.save(todo);
		return "redirect:/list-todos";//Redirects to list-todos method showTodos.. rather than just the jsp file
	}
}

spring-boot-workspace/first-spring-boot-web-application/src/main/java/com/springboot/web/firstspringbootwebapplication/controllers/WelcomeController.java
package com.springboot.web.firstspringbootwebapplication.controllers;

import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

//Login => "Hello World" @RequestParam String name, ModelMap model
@Controller
//dont need to store name in session bc of spring security @SessionAttributes("name")
public class WelcomeController {
	
	@RequestMapping(value ="/", method = RequestMethod.GET)
	public String showWelcomePage(ModelMap model) {
		model.put("activeTab", "welcome");
		model.put("name", getLoggedinUserName());
		return "welcome";
	}

	//Get logged in userId and Pass from spring security
	private String getLoggedinUserName() {
		Object principal = SecurityContextHolder.getContext().getAuthentication().getPrincipal();
		if(principal instanceof UserDetails) {
			return ((UserDetails)principal).getUsername();
		}
		return principal.toString();
	}
}

spring-boot-workspace/first-spring-boot-web-application/src/main/webapp/WEB-INF/jsp/error.jsp
<%@include file="common/header.jspf" %>
<%@include file="common/navigation.jspf" %>
<div class="container">
	An exception occured! Please contact support!
	<div>occurred at ${url} <br/>${exception}</div>
</div>
<%@include file="common/footer.jspf" %>

spring-boot-workspace/first-spring-boot-web-application/src/main/webapp/WEB-INF/jsp/list-todos.jsp
<%@include file="common/header.jspf" %>
<%@include file="common/navigation.jspf" %>
	<div class="container">
		<table class="table table-striped">
			<caption>Your todos are</caption>
			<thead>
				<tr>
					<th>Description</th>
					<th>Date</th>
					<th>Finished?</th>
				</tr>
			</thead>
			<tbody>
				<c:forEach items = "${todos}" var="todo">
					<tr>
						<td>${todo.descr}</td>
						<td><fmt:formatDate value="${todo.targetDate}" pattern="dd/MMM/yyyy"/></td>
						<td>${todo.done}</td>
						<td><a type="button" class="btn btn-success" href="/update-todo?id=${todo.id}">Update</a></td>
						<td><a type="button" class="btn btn-warning" href="/delete-todo?id=${todo.id}">Delete</a></td>
					</tr>
				</c:forEach>
			</tbody>
		</table>
		<div><a class="button" href="/add-todo">Add a Todo</a></div>
	</div>
	
<%@include file="common/footer.jspf" %>

spring-boot-workspace/first-spring-boot-web-application/src/main/webapp/WEB-INF/jsp/login.jsp
<%@include file="common/header.jspf" %>
<%@include file="common/navigation.jspf" %>
<div class="container">
	<form method="post" style="text-align:center;">
		<h1>Login</h1>
		<div><font color="red">${errorMessage}</font></div>
		<label style="">Credentials: </label>
		<div><input type="text" name="name" style="width:20%; text-align:center;" placeholder="Username"/></div>
		<div><input type="text" name="password" style="width:20%; text-align:center;" placeholder="password"/></div>
		<div><input type="submit" style="width:10%;"/></div>
	</form>
</div>
<%@include file="common/footer.jspf" %>

spring-boot-workspace/first-spring-boot-web-application/src/main/webapp/WEB-INF/jsp/todo.jsp
<%@include file="common/header.jspf" %>
<%@include file="common/navigation.jspf" %>
<div class="container">
	<form:form method="post" modelAttribute="todo">
	<form:hidden path="id"/>
	<form:hidden path="user"/>
		<fieldset class="form-group">
			<form:label path="descr">Description</form:label>
			<form:input path="descr" type="text" class="form-control" required="required" />
		<div><font color="red">${errorMessage}</font></div>
		</fieldset>
		<fieldset class="form-group">
			<form:label path="targetDate">Date</form:label>
			<form:input path="targetDate" type="text" class="form-control" required="required" />
		<div><font color="red">${errorMessage}</font></div>
		</fieldset>
		<button type="submit" class="btn btn-success">Add</button>
	</form:form>
</div>
<%@include file="common/footer.jspf" %>

spring-boot-workspace/first-spring-boot-web-application/src/main/webapp/WEB-INF/jsp/welcome.jsp
<%@include file="common/header.jspf" %>
<%@include file="common/navigation.jspf" %>
<div class="container">
	<form method="post" style="text-align:center;">
		<h1>Welcome ${name}</h1>
		<a href="list-todos">Click here to manage Todos</a>
		<hr/>
	</form>
</div>
<%@include file="common/footer.jspf" %>